//! Fixed option lists for dropdowns. These match the string forms used in
//! `WorldDto` (`Debug` of the enum in `worlds.rs`), plus star colour codes and
//! route enums via `serde` rename rules.

pub const STAR_COLOUR_CODES: &[&str] = &["O", "B", "A", "F", "G", "K", "M"];

pub fn star_colour_name(code: &str) -> &'static str {
    match code {
        "O" => "blue hypergiant",
        "B" => "blue-white",
        "A" => "white",
        "F" => "yellow-white",
        "G" => "yellow",
        "K" => "orange dwarf",
        "M" => "red dwarf",
        _ => "unknown",
    }
}

pub const WORLD_TYPES: &[&str] = &[
    "AgriWorld",
    "Asteroid",
    "BastionWorld",
    "DeathWorld",
    "DeadWorld",
    "ExtractiveColony",
    "FeralWorld",
    "FeudalWorld",
    "ForgeWorld",
    "FrontierWorld",
    "HiveWorld",
    "IndustrialWorld",
    "Orbital",
    "PenalWorld",
    "PlanetaryDump",
    "PlanetaryMonument",
    "PleasureWorld",
    "ResearchStation",
    "ShrineWorld",
    "TombWorld",
    "WarpLostWorld",
    "Worldship",
    "XenosWorld",
];

pub const ATMOSPHERES: &[&str] = &[
    "Airless",
    "Breathable",
    "Corrosive",
    "Exotic",
    "Thin",
    "Tainted",
    "Toxic",
];

pub const TEMPERATURES: &[&str] = &["Freezing", "Cold", "Temperate", "Hot", "Boiling"];

pub const BIOSPHERES: &[&str] = &[
    "Nonexistent",
    "Minimal",
    "Thriving",
    "Poisoned",
    "XenoHybrid",
    "XenoDominance",
];

pub const POPULATIONS: &[&str] = &[
    "Uninhabited",
    "Minimal",
    "LightlyPopulated",
    "SoleSettlement",
    "DenselyPopulated",
    "ExtremelyDense",
];

pub const TECH_LEVELS: &[&str] = &[
    "Primitive",
    "Low",
    "Standard",
    "High",
    "XenoHybrid",
    "Archaeotech",
];

pub const GOVERNMENTS: &[&str] = &[
    "BalkanizedLocalFactions",
    "ChaosCult",
    "ClansTribes",
    "Communards",
    "CorruptAristocrats",
    "Demagogue",
    "EcclesiarchicalAppointee",
    "ElitistTyrant",
    "ExploratorAuthority",
    "GuildsCombine",
    "Hereteks",
    "HereticalImperialCult",
    "InfractionistGang",
    "LocalReligiousAuthorities",
    "LoyalistMassMovement",
    "MagistrateCouncil",
    "MechanicusForgeLord",
    "Megacorporations",
    "MilitaryGovernor",
    "None",
    "PopulistTyrant",
    "PuppetGovernment",
    "RevolutionaryJunta",
    "RogueTraderDynasty",
    "ShadowyPsykerCabal",
    "TraditionalOligarchy",
    "TraditionalistAristocracy",
    "Warlords",
    "WarriorAristocracy",
    "XenosOverlords",
];

pub const NOTABLE_FEATURES: &[&str] = &[
    "Abhumans",
    "AlteredHumans",
    "AncientArchive",
    "AncientTombs",
    "ArchaeotechRuins",
    "BlindingMists",
    "CelestialPhenomena",
    "ChaosCultists",
    "CivilWar",
    "ColdWar",
    "CrumblingArcologies",
    "DaemonicCorruption",
    "DangerousWildlife",
    "DesertWorld",
    "DeviantReligion",
    "EugenicCult",
    "ExtremeEnvironment",
    "FactionalFragmentation",
    "FailedParadise",
    "FlyingCities",
    "ForbiddenTech",
    "ForeignControl",
    "FreakGeology",
    "FreakWeather",
    "Freeport",
    "FriendlyXenos",
    "FrozenWorld",
    "GoldRush",
    "GreatWork",
    "HeavyIndustry",
    "HeavyMining",
    "Hereteks",
    "HolyWar",
    "HostileBiosphere",
    "HostileXenos",
    "ImpendingDoom",
    "ImperialKnights",
    "ImportantShrine",
    "InquisitionOutpost",
    "JungleWorld",
    "Libertines",
    "LocalSpecialty",
    "LocalTech",
    "MajorSpaceyard",
    "MartialLaw",
    "MassPanic",
    "MinimalContact",
    "Missionaries",
    "MutantHordes",
    "NavalBlockade",
    "NavalOutpost",
    "NavigatorHouse",
    "NomadicCities",
    "NotableLocal",
    "OceanWorld",
    "OutOfContact",
    "Pandemic",
    "PilgrimageSite",
    "PocketEmpire",
    "PoliceState",
    "PopularUprising",
    "PowerfulCriminals",
    "PowerfulNobles",
    "PrimitiveXenos",
    "Prosperous",
    "PsykerAcademy",
    "PsykerCult",
    "Quarantined",
    "Radioactive",
    "RecentlyRediscovered",
    "ScholaProgenium",
    "SeagoingCities",
    "SealedMenace",
    "SecretMasters",
    "Sectarians",
    "SeismicInstability",
    "Separatists",
    "SilicaAnimus",
    "SoleSuppliers",
    "SororitasConvent",
    "SpaceHulks",
    "StrangeCustoms",
    "StrangeHatred",
    "SubsectorHegemon",
    "TechPriestCult",
    "TestSite",
    "TheSilentTrade",
    "TradeHub",
    "AdministrativeHub",
    "UnmappedWastes",
    "VastFortresses",
    "VerdantEcology",
    "WarZone",
    "WarpPhenomena",
    "WitchHunt",
    "XenoRuins",
    "Xenophiles",
    "Xenophobes",
    "XenosInfiltrators",
    "Zombies",
];

pub const ROUTE_TYPES: &[(&str, &str)] = &[
    ("stable_warp_lane", "stable warp lane"),
    ("charted_passage", "charted passage"),
    ("dangerous_passage", "dangerous passage"),
    ("secret_passage", "secret passage"),
];

pub const ROUTE_STABILITIES: &[(&str, &str)] = &[
    ("stable", "stable"),
    ("unstable", "unstable"),
    ("hazardous", "hazardous"),
    ("perilous", "perilous"),
];

pub const FACTION_INFLUENCES: &[(&str, &str)] = &[
    ("hidden", "hidden"),
    ("minor", "minor"),
    ("significant", "significant"),
    ("dominant", "dominant"),
];
