[alias]
sview = "run -p sectorforge-viewer --"
sbuild = "run -p sectorforge-builder --"
sba = "build --release --all-targets -p sector-generator -p sectorforge-viewer -p sectorforge-builder -p sectorforge-gui-core"
