//! Crate-internal declarative macros.

/// Generate `pub fn as_slug(&self) -> &'static str` for a fieldless enum from
/// explicit variant→slug pairs (IMPROVEMENT_REVIEW B-S3). The slugs are written
/// out verbatim — *not* derived from the variant name — so the serialized JSON /
/// markdown output stays byte-identical to the hand-written `match` blocks this
/// replaces. The generated `match` is exhaustive, so adding an enum variant
/// without a slug here is a compile error.
///
/// ```ignore
/// enum_slug!(Disposition {
///     Presence => "presence",
///     Influence => "influence",
/// });
/// ```
macro_rules! enum_slug {
    ($ty:ty { $($variant:ident => $slug:literal),+ $(,)? }) => {
        impl $ty {
            pub fn as_slug(&self) -> &'static str {
                match self {
                    $( Self::$variant => $slug, )+
                }
            }
        }
    };
    // `const` form for the few enums whose `as_slug` is a `const fn`.
    (const $ty:ty { $($variant:ident => $slug:literal),+ $(,)? }) => {
        impl $ty {
            pub const fn as_slug(&self) -> &'static str {
                match self {
                    $( Self::$variant => $slug, )+
                }
            }
        }
    };
}

#[cfg(test)]
mod slug_parity_tests {
    //! Guard: for every `Serialize` enum whose `as_slug()` is generated by
    //! [`enum_slug!`], the slug literal must equal the serde wire string for
    //! **every** variant. The slugs are written by hand in the `enum_slug!`
    //! call while the wire string comes from `#[serde(rename_all = ...)]`; this
    //! test fails the moment those two ever diverge (a renamed variant, a typo,
    //! a forgotten `rename_all`, a hand-edited slug). It is the single source of
    //! truth that the two encodings stay byte-identical.
    //!
    //! Two `enum_slug!` enums are deliberately absent: `ValidationCode` and
    //! `analysis::importance::KindGroup` do not derive `Serialize`, so there is
    //! no serde wire string to compare against — their slugs are emitted
    //! directly via `as_slug()` and have no `rename_all` to drift from.

    /// For each `Type => [variants...]`, assert the serde wire string equals
    /// `as_slug()` for every listed variant. The `enum_slug!`-generated
    /// `as_slug` `match` is already exhaustive, so a variant added without a
    /// slug is a compile error there; listing every variant here adds the
    /// reverse guard — that the slug matches what serde emits.
    macro_rules! assert_slug_serde_parity {
        ( $( $ty:path => [ $($variant:ident),+ $(,)? ] ),+ $(,)? ) => {
            $( $(
                {
                    let v = <$ty>::$variant;
                    let wire = serde_json::to_string(&v).unwrap();
                    let wire = wire.trim_matches('"');
                    assert_eq!(
                        wire,
                        v.as_slug(),
                        "{}::{}: serde wire string {:?} != as_slug() {:?}",
                        stringify!($ty),
                        stringify!($variant),
                        wire,
                        v.as_slug(),
                    );
                }
            )+ )+
        };
    }

    #[test]
    fn enum_slug_matches_serde_for_every_variant() {
        use crate::sector_model::{
            ClaimType, DominanceState, FactionInfluence, RouteKind, RouteStability, RouteType,
            RouteViewMode, SystemKind, SystemState,
        };

        assert_slug_serde_parity! {
            // ── validate ────────────────────────────────────────────────
            crate::validation::Severity => [Error, Warning, Info],

            // ── analysis::personae ──────────────────────────────────────
            crate::personae::DominanceTier => [
                Presence, Influence, Contested, Controlled, Stronghold,
            ],
            crate::personae::FactionTier => [Overall, Subfaction, Force],
            crate::personae::SystemSlot => [
                Sovereign, OrbitalController, EconomicHegemon, HiddenMaster,
            ],

            // ── analysis::missions ──────────────────────────────────────
            crate::missions::MissionKind => [
                Investigate, Escort, Sabotage, Diplomacy, Assassination, Recovery,
                Defense, Exploration,
            ],
            crate::missions::MissionScale => [OneShot, ShortArc, CampaignArc],
            crate::missions::MissionVisibility => [
                Public, Restricted, Secret, Misinformation,
            ],

            // ── analysis::hooks ─────────────────────────────────────────
            crate::hooks::HookKind => [
                CounterInfiltration, Reconquest, LostPassage, ConvoyEscort, BlockadeRun,
                HoldTheLine, SealedTombs, CrushUprising, SealedSystem, CultPurge,
                DiplomaticCrisis, SuccessionDispute, StarvingWorld, LifelineLane,
            ],

            // ── analysis::briefing ──────────────────────────────────────
            crate::briefing::AudiencePreset => [
                GmFullTruth, ImperialNavy, Inquisition, RogueTrader, LocalGovernor,
                PublicAtlas,
            ],

            // ── analysis::search ────────────────────────────────────────
            crate::search::StanceName => [Allied, Aligned, Neutral, Rival, Hostile, AtWar],
            crate::search::RegionKindName => [
                WarpStorm, Turbulence, CalmCorridor, Blackout, Anomaly,
            ],
            crate::search::SystemStateName => [
                Pacified, Fragmented, Blockaded, Warzone, Infiltrated, Quarantined,
                Uncharted,
            ],
            // NOTE: PascalCase serde, not snake_case — the parity check covers it.
            crate::search::PresenceName => [Hidden, Minor, Significant, Dominant],

            // ── analysis::interestingness ───────────────────────────────
            crate::interestingness::ProfileId => [
                PoliticalSandbox, GrimCollapse, Mercantile, Villainous, Frontier,
            ],

            // ── analysis::intel ─────────────────────────────────────────
            crate::intel::IntelSource => [
                DirectObservation, AstropathicReport, InquisitorialAnalysis, Rumor,
                ImaginedDeduction,
            ],
            crate::intel::PropagandaState => [
                None, OfficialPacified, OfficialContested, OfficialLost, Counterfactual,
            ],
            crate::intel::ClassifiedState => [
                Public, CodexRedactus, PurgatusSigillum, ExterminatusFlag,
            ],

            // ── analysis::economy ───────────────────────────────────────
            crate::economy::TitheStatus => [
                Surplus, Adequate, Strained, Delinquent, Failed, Falsified,
            ],
            crate::economy::SupplyRisk => [Stable, Vulnerable, Disrupted, Collapsing],
            crate::economy::StrategicPriority => [
                Low, Local, Subsector, Sector, CrusadeLevel,
            ],

            // ── analysis::analytics ─────────────────────────────────────
            crate::analytics::FlagSeverity => [Info, Warning, Error],

            // ── analysis::prose ─────────────────────────────────────────
            crate::prose::ProseTone => [Gazetteer, Dispatch],

            // ── analysis::relations ─────────────────────────────────────
            crate::relations::Stance => [Allied, Aligned, Neutral, Rival, Hostile, AtWar],
            crate::relations::RelationAttitude => [
                Allied, Friendly, Transactional, Suspicious, Hostile, ExistentialEnemy,
            ],
            crate::relations::TreatyStatus => [
                None, Pact, Truce, Vassalage, Charter, Nonaggression, Vendetta,
            ],

            // ── analysis::history ───────────────────────────────────────
            crate::history::EventKind => [
                Foundation, Discovery, Annexation, ImperialMandateGranted, Consecration,
                CommercialCharter, DynasticClaim, Secession, Uprising, Reconquest, Purge,
                CultExposed, NecronAwakening, TyranidContact, OrkWaaagh, QuarantineDeclared,
                Blockade, WarpStormSurge, TauContact, AeldariActivity, ChaosIncursion,
            ],
            crate::history::HistoryEntityKind => [
                Sector, System, World, Route, Faction, Claim, Subsector, Region,
            ],
            crate::history::HistoryConsequenceKind => [
                WorldSettled, ClaimEstablished, ControlShift, ConflictEscalated, RouteHazard,
                BlockadeCreated, QuarantineDeclared, FactionMemory, SubsectorCapitalNamed,
                RegionRecorded,
            ],

            // ── loading::config ─────────────────────────────────────────
            crate::config::PlacementMode => [UniformGrid, WeightedGrid, Clustered],
            crate::config::WorldSelectionMode => [WeightedRows],
            crate::config::OutputFormat => [Json, Markdown, Bitmap, Svg, Html],
            crate::config::HtmlTheme => [Dark, Parchment, Hololithic],

            // ── gen::surface_region ─────────────────────────────────────
            crate::surface_region::RegionKind => [
                Capital, Hive, Underhive, ForgeComplex, ShrineContinent, AgriBelt,
                CardinalSpire, KnightHousehold, Wilderness, TombComplex, Hideout, Other,
            ],

            // ── gen::regions ────────────────────────────────────────────
            crate::regions::RegionConditionKind => [
                WarpStorm, Turbulence, CalmCorridor, Blackout, Anomaly, NecropolisDrift,
                BeaconChain, EmpyricBleed,
            ],

            // ── gen::archetypes ─────────────────────────────────────────
            crate::archetypes::NecronPhase => [None, Dormant, Awakening, Awake],
            crate::archetypes::TyranidStage => [None, Inhabited, Besieged, Consumed],
            crate::archetypes::GscStage => [
                None, Rumor, HiddenCell, DistrictControl, ParallelGovernment, Uprising,
                PlanetarySeizure,
            ],
            crate::archetypes::TauSphereBand => [None, Contact, Fringe, Client, Core],

            // ── gen::orbital_assets ─────────────────────────────────────
            crate::orbital_assets::OrbitalAssetKind => [
                Station, Shipyard, DefensePlatform, BlockadeFleet,
            ],

            // ── gen::sites ──────────────────────────────────────────────
            crate::sites::SiteKind => [
                GovernorsPalace, CathedralSpire, Manufactorum, UnderhiveSumpCity, VoidElevator,
                StarFortDockyard, QuarantineZone, XenosRuin, PilgrimNecropolis, AstropathicChoir,
                ArbitesPrecinct, DataVault, DisputedShrine, PenalMine, BlackMarketEnclave,
                CultSafehouse, CrashedVoidship, AgriBeltGranary, ForgeReactor, TombComplex,
                NavalAnchorage,
            ],
            crate::sites::SiteStatus => [
                Active, Restricted, Abandoned, Quarantined, Sealed, Contested, UnderConstruction,
            ],

            // ── model::sector_model ─────────────────────────────────────
            RouteViewMode => [Detailed, TopLevel],
            SystemKind => [Star, SpecialLocation, BlackHole, WarpAnomaly, SpaceStation],
            RouteKind => [Warp, Webway],
            RouteType => [
                StableWarpLane, ChartedPassage, SecretPassage, Webway, BlackShip, SmugglingLane,
            ],
            RouteStability => [Stable, Unstable, Hazardous, Perilous],
            FactionInfluence => [Hidden, Minor, Significant, Dominant],
            DominanceState => [
                Rumored, Presence, Influence, Contested, Controlled, Stronghold,
            ],
            ClaimType => [
                LegalSovereignty, ImperialMandate, TreatyRight, ReligiousMandate, DynasticRight,
                CommercialCharter, MilitaryOccupation, AncientDomain, HuntingGround, CovertWrit,
                Rebellion,
            ],
            SystemState => [
                Pacified, Fragmented, Blockaded, Warzone, Infiltrated, Quarantined, Uncharted,
            ],

            // ── export::map_theme ───────────────────────────────────────
            crate::map_theme::RouteLineMode => [Standard, HazardWeighted],
            crate::map_theme::LabelDensity => [All, ImportantOnly, None],
            crate::map_theme::LegendStyle => [Full, Compact, Hidden],
            crate::map_theme::SymbolSet => [Standard, Tactical, Redacted],

            // ── export::segmentum ───────────────────────────────────────
            crate::segmentum::FactionMode => [Shared, Independent],
            crate::segmentum::BorderOrientation => [EastWest, NorthSouth],

            // ── export::heatmap ─────────────────────────────────────────
            crate::heatmap::HeatmapMode => [
                Off, Control, Military, Trade, Industrial, Covert, Faith, Threat, Intel, Tension,
                TradeVolume, FoodOutput, TitheStress, SupplyVulnerability, ConflictIntensity,
            ],
            crate::heatmap::StabilityDimension => [
                PublicOrder, Corruption, Fear, RebellionRisk, XenosThreat, WarpInstability,
                FamineResourceStress,
            ],
        }
    }
}
